import strutils
import ospaths
const headerswitch = currentSourcePath().splitPath().head & "/nx/include/switch.h"
import libnx/types
import libnx/result
import libnx/nro
import libnx/nacp
import libnx/tls
import libnx/cache
import libnx/svc
import libnx/tmem
import libnx/shmem
import libnx/mutex
import libnx/rwlock
import libnx/condvar
import libnx/thread
import libnx/virtmem
import libnx/detect
import libnx/random
import libnx/jit
import libnx/ipc
import libnx/sm
import libnx/smm
import libnx/fs
import libnx/fsldr
import libnx/fspr
import libnx/acc
import libnx/apm
import libnx/applet
import libnx/audin
import libnx/audout
import libnx/csrng
import libnx/fatal
import libnx/time
import libnx/usb
import libnx/hid
import libnx/irs
import libnx/pl
import libnx/vi
import libnx/nv
import libnx/nifm
import libnx/ns
import libnx/ldr
import libnx/pm
import libnx/set
import libnx/lr
import libnx/spl
import libnx/gfx
import libnx/binder
import libnx/parcel
import libnx/buffer_producer
import libnx/ioctl
import libnx/nvioctl
import libnx/nvgfx
import libnx/env
import libnx/nxlink
import libnx/utf
import libnx/console
import libnx/usb_comms
import libnx/fs_dev
import libnx/romfs_dev
import libnx/socket
