import strutils
import ospaths
const headerswitch = currentSourcePath().splitPath().head & "/nx/include/switch.h"
import libnx_wrapper/types
import libnx_wrapper/result
import libnx_wrapper/nro
import libnx_wrapper/nacp
import libnx_wrapper/tls
import libnx_wrapper/cache
import libnx_wrapper/svc
import libnx_wrapper/tmem
import libnx_wrapper/shmem
import libnx_wrapper/mutex
import libnx_wrapper/rwlock
import libnx_wrapper/condvar
import libnx_wrapper/thread
import libnx_wrapper/virtmem
import libnx_wrapper/detect
import libnx_wrapper/random
import libnx_wrapper/jit
import libnx_wrapper/ipc
import libnx_wrapper/sm
import libnx_wrapper/smm
import libnx_wrapper/fs
import libnx_wrapper/fsldr
import libnx_wrapper/fspr
import libnx_wrapper/acc
import libnx_wrapper/apm
import libnx_wrapper/applet
import libnx_wrapper/audin
import libnx_wrapper/audout
import libnx_wrapper/csrng
import libnx_wrapper/fatal
import libnx_wrapper/time
import libnx_wrapper/usb
import libnx_wrapper/hid
import libnx_wrapper/irs
import libnx_wrapper/pl
import libnx_wrapper/vi
import libnx_wrapper/nv
import libnx_wrapper/nifm
import libnx_wrapper/ns
import libnx_wrapper/ldr
import libnx_wrapper/pm
import libnx_wrapper/set
import libnx_wrapper/lr
import libnx_wrapper/spl
import libnx_wrapper/gfx
import libnx_wrapper/binder
import libnx_wrapper/parcel
import libnx_wrapper/buffer_producer
import libnx_wrapper/ioctl
import libnx_wrapper/nvioctl
import libnx_wrapper/nvgfx
import libnx_wrapper/env
import libnx_wrapper/nxlink
import libnx_wrapper/utf
import libnx_wrapper/console
import libnx_wrapper/usb_comms
import libnx_wrapper/fs_dev
import libnx_wrapper/romfs_dev
import libnx_wrapper/socket
