import strutils
import ospaths
const headerswitch = currentSourcePath().splitPath().head & "/nx/include/switch.h"
import libnx/wrapper/types
import libnx/wrapper/result
import libnx/wrapper/nro
import libnx/wrapper/nacp
import libnx/wrapper/tls
import libnx/wrapper/cache
import libnx/wrapper/svc
import libnx/wrapper/tmem
import libnx/wrapper/shmem
import libnx/wrapper/mutex
import libnx/wrapper/rwlock
import libnx/wrapper/condvar
import libnx/wrapper/thread
import libnx/wrapper/virtmem
import libnx/wrapper/detect
import libnx/wrapper/random
import libnx/wrapper/jit
import libnx/wrapper/ipc
import libnx/wrapper/sm
import libnx/wrapper/smm
import libnx/wrapper/fs
import libnx/wrapper/fsldr
import libnx/wrapper/fspr
import libnx/wrapper/acc
import libnx/wrapper/apm
import libnx/wrapper/applet
import libnx/wrapper/audin
import libnx/wrapper/audout
import libnx/wrapper/csrng
import libnx/wrapper/fatal
import libnx/wrapper/time
import libnx/wrapper/usb
import libnx/wrapper/hid
import libnx/wrapper/irs
import libnx/wrapper/pl
import libnx/wrapper/vi
import libnx/wrapper/nv
import libnx/wrapper/nifm
import libnx/wrapper/ns
import libnx/wrapper/ldr
import libnx/wrapper/pm
import libnx/wrapper/set
import libnx/wrapper/lr
import libnx/wrapper/spl
import libnx/wrapper/gfx
import libnx/wrapper/binder
import libnx/wrapper/parcel
import libnx/wrapper/buffer_producer
import libnx/wrapper/ioctl
import libnx/wrapper/nvioctl
import libnx/wrapper/nvgfx
import libnx/wrapper/env
import libnx/wrapper/nxlink
import libnx/wrapper/utf
import libnx/wrapper/console
import libnx/wrapper/usb_comms
import libnx/wrapper/fs_dev
import libnx/wrapper/romfs_dev
import libnx/wrapper/socket
