## *
##  @file switch.h
##  @brief Central Switch header. Includes all others.
##  @copyright libnx Authors
##

import
  switch/types, switch/result, switch/nro, switch/nacp, switch/arm/tls,
  switch/arm/cache, switch/arm/counter, switch/kernel/svc, switch/kernel/wait,
  switch/kernel/tmem, switch/kernel/shmem, switch/kernel/mutex,
  switch/kernel/event, switch/kernel/levent, switch/kernel/uevent,
  switch/kernel/utimer, switch/kernel/rwlock, switch/kernel/condvar,
  switch/kernel/thread, switch/kernel/semaphore, switch/kernel/virtmem,
  switch/kernel/detect, switch/kernel/random, switch/kernel/jit,
  switch/kernel/barrier, switch/sf/hipc, switch/sf/cmif, switch/sf/service,
  switch/sf/sessionmgr, switch/sf/tipc, switch/services/sm, switch/services/smm,
  switch/services/fs, switch/services/fsldr, switch/services/fspr,
  switch/services/acc, switch/services/apm, switch/services/applet,
  switch/services/async, switch/services/audctl, switch/services/audin,
  switch/services/audout, switch/services/audrec, switch/services/audren,
  switch/services/auddev, switch/services/hwopus, switch/services/csrng,
  switch/services/lbl, switch/services/i2c, switch/services/gpio,
  switch/services/uart, switch/services/bpc, switch/services/pcv,
  switch/services/clkrst, switch/services/fan, switch/services/pgl,
  switch/services/psm, switch/services/spsm

export
  types, result, nro, nacp, tls,
  cache, counter, svc, wait,
  tmem, shmem, mutex,
  event, levent, uevent,
  utimer, rwlock, condvar,
  thread, semaphore, virtmem,
  detect, random, jit,
  barrier, hipc, cmif, service,
  sessionmgr, tipc, sm, smm,
  fs, fsldr, fspr,
  acc, apm, applet,
  async, audctl, audin,
  audout, audrec, audren,
  auddev, hwopus, csrng,
  lbl, i2c, gpio,
  uart, bpc, pcv,
  clkrst, fan, pgl,
  psm, spsm


import
  switch/services/fatal, switch/services/time, switch/services/usb,
  switch/services/usbds, switch/services/usbhs, switch/services/hid,
  switch/services/hidbus, switch/services/hiddbg, switch/services/hidsys,
  switch/services/irs, switch/services/pl, switch/services/vi, switch/services/nv,
  switch/services/nifm, switch/services/nim, switch/services/ns,
  switch/services/ldr, switch/services/ro, switch/services/tc, switch/services/ts,
  switch/services/pm, switch/services/set, switch/services/ssl, switch/services/lr,
  switch/services/bt, switch/services/btdrv, switch/services/btm,
  switch/services/btmu, switch/services/btmsys, switch/services/spl,
  switch/services/ncm, switch/services/psc, switch/services/caps,
  switch/services/capsa, switch/services/capsc, switch/services/capsdc,
  switch/services/capsu, switch/services/capssc, switch/services/capssu,
  switch/services/capmtp, switch/services/nfc, switch/services/wlaninf,
  switch/services/pctl, switch/services/pdm, switch/services/grc,
  switch/services/friends, switch/services/notif, switch/services/mii,
  switch/services/miiimg, switch/services/ldn, switch/services/lp2p,
  switch/services/news, switch/services/ins, switch/services/ectx,
  switch/services/avm, switch/services/mm, switch/display/binder,
  switch/display/parcel, switch/display/buffer_producer,
  switch/display/native_window, switch/display/framebuffer, switch/nvidia/ioctl,
  switch/nvidia/graphic_buffer, switch/nvidia/fence, switch/nvidia/map,
  switch/nvidia/address_space, switch/nvidia/channel, switch/nvidia/gpu,
  switch/nvidia/gpu_channel, switch/audio/driver, switch/applets/libapplet,
  switch/applets/album_la, switch/applets/friends_la, switch/applets/hid_la,
  switch/applets/mii_la, switch/applets/nfp_la, switch/applets/nifm_la,
  switch/applets/pctlauth, switch/applets/psel, switch/applets/error,
  switch/applets/swkbd, switch/applets/web, switch/runtime/env,
  switch/runtime/hosversion, switch/runtime/diag, switch/runtime/nxlink,
  switch/runtime/resolver, switch/runtime/pad, switch/runtime/ringcon,
  switch/runtime/btdev, switch/runtime/util/utf, switch/runtime/devices/console,
  switch/runtime/devices/usb_comms, switch/runtime/devices/fs_dev,
  switch/runtime/devices/romfs_dev, switch/runtime/devices/socket,
  switch/crypto/aes, switch/crypto/aes_cbc, switch/crypto/aes_ctr,
  switch/crypto/aes_xts, switch/crypto/cmac, switch/crypto/sha256,
  switch/crypto/sha1, switch/crypto/hmac, switch/crypto/crc

export
  fatal, time, usb,
  usbds, usbhs, hid,
  hidbus, hiddbg, hidsys,
  irs, pl, vi, nv,
  nifm, nim, ns,
  ldr, ro, tc, ts,
  pm, set, ssl, lr,
  bt, btdrv, btm,
  btmu, btmsys, spl,
  ncm, psc, caps,
  capsa, capsc, capsdc,
  capsu, capssc, capssu,
  capmtp, nfc, wlaninf,
  pctl, pdm, grc,
  friends, notif, mii,
  miiimg, ldn, lp2p,
  news, ins, ectx,
  avm, mm, binder,
  parcel, buffer_producer,
  native_window, framebuffer, ioctl,
  graphic_buffer, fence, map,
  address_space, channel, gpu,
  gpu_channel, driver, libapplet,
  album_la, friends_la, hid_la,
  mii_la, nfp_la, nifm_la,
  pctlauth, psel, error,
  swkbd, web, env,
  hosversion, diag, nxlink,
  resolver, pad, ringcon,
  btdev, utf, console,
  usb_comms, fs_dev,
  romfs_dev, socket,
  aes, aes_cbc, aes_ctr,
  aes_xts, cmac, sha256,
  sha1, hmac, crc
